spring:
  datasource:
    url: jdbc:h2:mem:pricingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
